set default port to 5901, detect if the DISPLAY is valid

diff --git a/startvnc b/startvnc
--- a/startvnc
+++ b/startvnc
@@ -10,8 +10,9 @@
 # What's the script name
 SCRIPTNAME="startvnc"
 
+VNCSERVER=0vncserver
 # Where the x0vncserver executable is located, default:
-VNCSERVER="/usr/bin/x0vncserver"
+XVNCSERVER="/usr/bin/x$VNCSERVER"
 
 # Set home directory
 HOMEDIR=${HOME}
@@ -28,8 +29,8 @@ PASSWDFILE="${VNCDIR}/passwd"
 # Leave this on ":0", since we want to log in to the actual session
 DISPLAY=":0"
 
-# Set the port (default 5900)
-VNCPORT="5900"
+# Set the port (default 5901)
+VNCPORT="5901"
 
 # PID of the actual VNC server running
 # The PID is actually created this way, so it is compatible with the vncserver command
@@ -45,7 +46,7 @@ NOTRUNNING="[\033[1;31mnot running\033[0m]"
 
 # Function to get the process id of the VNC Server
 fn_pid() {
-    CHECKPID=$(ps -fu ${USER} | grep "[x]0vncserver" | awk '{print $2}')
+    CHECKPID=$(ps -fu ${USER} | grep "[x]$VNCSERVER" | awk '{print $2}')
     if [[ ${CHECKPID} =~ ^[0-9]+$ ]] 
     then
         VAR=${CHECKPID}
@@ -71,6 +72,13 @@ then
     exit 1
 fi
 
+if xdpyinfo -display "$DISPLAY" >/dev/null 2>&1;then
+    echo "user $USER can connect to display $DISPLAY"
+else
+    echo "user $USER cannot connect to display $DISPLAY"
+    exit 1
+fi
+
 case "$1" in
     start)
         echo -n "Starting VNC Server on display ${DISPLAY} "
@@ -81,7 +89,7 @@ case "$1" in
             echo -e "VNC Server is running (pid: ${VAR})"
 	    echo
         else
-            ${VNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
+            ${XVNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
 	    if [ $? -eq 0 ]
 	    then
             	fn_pid
@@ -107,7 +115,7 @@ case "$1" in
 
             if [ $? -eq 0 ]
             then 
-                ${VNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
+                ${XVNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
                 echo -e ${OK}
 		echo
                 fn_pid 
@@ -122,7 +130,7 @@ case "$1" in
 
         else
 
-            ${VNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
+            ${XVNCSERVER} -display ${DISPLAY} -passwordfile ${PASSWDFILE} -rfbport ${VNCPORT} >> ${LOGFILE} 2>&1 &
             if [ $? -eq 0 ]
             then
                 echo -e ${OK}
